### ISSUE TITLE
OSC : Create an interface for the app with login and sign-in buttons

### ISSUE THREAD

**Issue by Kapoor-0905** [upes-open/OSC-Sports-App#1]

**Comment by Shreya-bansall** [comment]
Here is the link: https://www.figma.com/proto/ndvQ53SGUAm8oXFssHT8FJ/Sports-App?node-id=2%3A2&scaling=scale-down&page-id=0%3A1

**Comment by Kapoor-0905** [comment]
> Here is the link: https://www.figma.com/proto/ndvQ53SGUAm8oXFssHT8FJ/Sports-App?node-id=2%3A2&scaling=scale-down&page-id=0%3A1

Hii Shreya the interface is good but it must be created on the tech stack mentioned i.e. react.
you can create the same on react too

**Comment by Charu-2718** [comment]
Can I do this part?

**Comment by Kapoor-0905** [comment]
> Can I do this part?

sure assigned to you

**Comment by Kapoor-0905** [comment]
Issue completed
